apiVersion: apps/v1
kind: Deployment
metadata:
  name: client_pod
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: dipsy1234/l4t-pytorch
        command: ["python3"]
        args: ["/model_train_test.py"]
        volumeMounts:
        - name: cuda-libs
          mountPath: /usr/local/cuda-libs
        - name: cudnn-lib
          mountPath: /usr/lib/aarch64-linux-gnu
        env:
        - name: LD_LIBRARY_PATH
          value: "/usr/local/cuda-libs:/usr/local/cuda/lib64:/usr/lib/aarch64-linux-gnu"
      volumes:
      - name: cuda-libs
        hostPath:
          path: /usr/local/cuda/lib64
      - name: cudnn-lib
        hostPath:
          path: /usr/lib/aarch64-linux-gnu
